spring.application.name=reservation-system

spring.datasource.url=jdbc:postgresql://localhost:55432/postgres?options=-c%20TimeZone=UTC
spring.datasource.username=postgres
spring.datasource.password=root

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true